BUPT/ai-ml.club

README.md
=> Add "Papers & Codes" Section and a new challenge.

docs/posts/2018-10-14-google-tpu-colab.md
=> My two slides - add club blog #24

docs/_posts/2019-01-20-seminar-meeting-minutes-22.md
<https://github.com/BUPT/awesome-chatbot/issues/66>
=> 2019-1-20第二十三次CAIC活动纪要

docs/_posts/2019-05-05-roi.md
1. reference: BUPT/awesome-chatbot#93
2. Poster
3. paper name:None
4. No new friends~
=> roi change

docs/_data/navigation.yml, docs/_pages/papers.md, docs/_pages/wishlist.md
=> Add /papers to prepare for moving conversational-ai-club paper list here

docs/_pages/papers.md
1. reference: <https://github.com/BUPT/ai-ml.club/issues/107>
2. 824zzy: Oral  YapheeetS: Poster
3. ON-LSTM and DIORA, double crit to NLP!
4. Newcomer: Lunhua Zhang
=> docs($location): ON-LSTM and DIORA, double crit!

docs/_pages/papers.md
=> Poster - Speech2Face: Learning the Face Behind a Voice

docs/_pages/papers.md
> Past the paper name with the link that you want to present
[Generative Modeling with Sparse Transformers](https://openai.com/blog/sparse-transformer/)
#117 
> Whether you have a new friend comes with you to the club.
<sub>
<i>
Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://github.com/BUPT/ai-ml.club/wiki/Member-Manual">Member Manual</a>
</i>
</sub>
=> [Poster] Generative Modeling with Sparse Transformers

docs/_pages/papers.md
#117 
>
| --- | --- |
| Name | Detecting Curve Text in the Wild: New Dataset and New Solution |
| Year | 2017 |
| Author | Liu et. al. |
| GitHub | https://github.com/Yuliang-Liu/Curve-Text-Detector |
| Arxiv | https://arxiv.org/abs/1712.02170 |
> Everyone will be welcome. You can join or not join as you …
=> [poster] Detecting Curve Text in the Wild: New Dataset and New Solution

docs/_pages/papers.md
#129 
>
| --- | --- |
| Name | A Dual Reinforcement Learning Framework for Unsupervised Text Style Transfer  |
| Publish | ACL |
| Author | Fuli Luo et. al. |
| GitHub | https://github.com/luofuli/DualRL  |
| Blog | https://weibo.com/2678093863/HyxQaDFDK |
| Arxiv | …
=> Poster📰 - A Dual Reinforcement Learning Framework for Unsupervised Text Style Transfer, Fuli Luo et. al., ACL2019

docs/_data/authors.yml, docs/_pages/papers.md
#129 
>
| --- | --- |
| Name | Character Region Awareness for Text Detection |
| Author | Youngmin Baek et. al. |
| GitHub | https://github.com/guruL/Character-Region-Awareness-for-Text-Detection- |
| Arxiv | https://arxiv.org/abs/1904.01941 |
> Everyone will be welcome. You can join or …
=> Poster📰 - Character Region Awareness for Text Detection

.github/ISSUE_TEMPLATE/meeting-announcement.md, docs/_pages/about.md, docs/_posts/2019-06-16-seminar-meeting-minutes-2-14.md
Modified the meeting time from 9 pm to 10 pm
=> modified meeting time from 9pm to 10pm

docs/_posts/2019-06-18-text-style-transfer.md
=> 🗣Oral - Paper Title  

docs/_pages/papers.md
#140 
>
| --- | --- |
| Name | Dear Sir or Madam, May I Introduce the GYAFC Dataset: Corpus, Benchmarks and Metrics for Formality Style Transfer |
| Recommend | This is the dataset build for text style transfer, one of the authors is from Grammerly.com |
| Year | 2018  |
| Publish | NAACL-HLT |
| Author | …
=> 📰Poster: Dear Sir or Madam, May I Introduce the GYAFC Dataset: Corpus, Benchmarks and Metrics for Formality Style Transfer

docs/_pages/papers.md
#140 
| --- | --- |
| Name | Progressive Pose Attention Transfer for Person Image Generation |
| Recommendation | An Interesting attention during CNNs |
| Publish | CVPR |
| Author | Zhu, et. al. |
| Arxiv | https://arxiv.org/pdf/1904.03349 |
| Referrer | Newcomer | Bio
-- | -- | --
|@VDeamoV  | @WdBlink | 北邮的尹鹏宇，研究生一年级，医疗图像处理|
<sub>
<i>
</i>
</sub>
=> 📰Poster - Progressive Pose Attention Transfer for Person Image Generation

docs/_pages/papers.md
#140 
>
| --- | --- |
| Name | Taking A Closer Look at Domain Shift: Category-level Adversaries for Semantics Consistent Domain Adaptation |
| Recommendation | Consider the problem of unsupervised domain adaptation in semantic segmentation and an example for me to address you on some semi-supervised technique   |
| Publish | CVPR |
| Author | Yawei Luo, et. al. |
| GitHub | https://github.com/RoyalVane/CLAN |
| Arxiv | https://arxiv.org/abs/1809.09478 |
> Everyone will be welcome. You can …
=> 📰Poster: Taking A Closer Look at Domain Shift: Category-level Adversaries for Semantics Consistent Domain Adaptation

docs/_pages/papers.md
#140 
>
| --- | --- |
| Name | Dive into NN: Theory, Architecture and Initialization |
| Recommendation | The Mystery of Neural Network |
| Publish | GitHub |
| Author | Bo Lin |
| GitHub | https://github.com/linbo0518/Dive-into-NN |
> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change …
=> 🗣Oral - Dive into NN: Theory, Architecture and Initialization

docs/_pages/papers.md
#140 
>
| --- | --- |
| Name | XLNet: Generalized Autoregressive Pretraining for Language Understanding |
| Recommendation | Biggest Boomshakalaka at the end of June |
| Publish | Not received yet |
| Author | Yang, et. al. |
| GitHub | https://github.com/zihangdai/xlnet |
| Arxiv | https://arxiv.org/pdf/1906.08237.pdf |
> Everyone will …
=> 📰Poster - XLNet: Generalized Autoregressive Pretraining for Language Understanding

docs/_pages/papers.md, package.json
#151
>
| --- | --- |
| Name | 基于DGCNN和概率图的轻量级信息抽取模型 |
| Recommendation | 模型介绍由苏现林发在PaperWeekly，介绍非常详尽，有代码。苏现林所在的苏州火焰科技公司是NLP领域的一线公司，域名 birdbot.cn |
| Publish | PaperWeekly |
| Author | @bojone 苏剑林 |
| GitHub | https://github.com/bojone/kg-2019 |
| Blog | 苏剑林. (2019, Jun 03). …
=> 📰Poster - 基于DGCNN和概率图的轻量级信息抽取模型

docs/_pages/papers.md
#151
>
This oral is not a paper brief. It is an introduction to the idea of using NLP in Language Training.
> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. …
=> 📰Poster - Idea: Is it possible to put human being's characters model into NLP?

docs/_pages/papers.md
#151 
| Blog | Information |
| --- | --- |
| Name | Towards Reproducible Research with PyTorch Hub |
| Recommendation | Practical experience with Colab |
| Author | Team PyTorch |
| GitHub | None |
> Whether you have a new friend comes with you to the club.
| Referrer | Newcomer  | Bio |
| -------- | --------- | --- |
| @824zzy  | @TJH54 | 大家好我是北邮软件学院的滕静涵，研究生一年级，对AI/ML感兴趣但还是小白，希望能够跟随大佬们的步伐学习进步。|
| @824zzy  | @yyllyy0813 | 软件学院研一学生杨钰琳，想了解机器学习和深度学习方面的知识。 |
<sub>
<i>
</i>
</sub>
=> 📰Poster - Towards Reproducible Research with PyTorch Hub

docs/_pages/papers.md
> https://github.com/BUPT/ai-ml.club/issues/151
>
| --- | --- |
| Name | Multi-Label Image Recognition with Graph Convolutional Networks |
| Recommendation |引入GCN到multilabel classification |
| Publish |CVPR |
| Author | Zhao-Min Chen, Xiu-Shen Wei, Peng Wang, Yanwen Guo |
| GitHub |https://github.com/Megvii-Nanjing/ML_GCN |
| Blog |None | …
=> 📰Poster - multi-label with GCN

docs/_pages/papers.md
=> page s2e16

.github/ISSUE_TEMPLATE/meeting-announcement.md
issues templete
added people attended
=> issues templete

docs/_pages/papers.md
#164 
| --- | --- |
| Name | Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context |
| Recommendation | Transformer的变种，可以学习超长的上下文关系 |
| Year | 2019-01 |
| Publish | ACL 2019 long paper |
| Author | Zihang Dai, et. al. |
| GitHub | https://github.com/kimiyoung/transformer-xl |
| Blog | None |
| Arxiv | https://arxiv.org/abs/1901.02860 |
<sub>
<i>
</i>
</sub>
=> 📰Poster - Transformer-XL：学习超长上下文关系

docs/_pages/papers.md
#164 
Select one of the following selections for Oral or Post>e>r:
1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q>/A.
1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.
Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)
| --- | --- |
| Name | MRI brain tumor segmentation using autoencoder regularization |
| Recommendation | MICCAI 2018 workshop BraTS分割第一名 |
| Year | 2018 |
| Publish | MICCAI |
| Author | Andriy Myronenko, et. al. |
| GitHub | none |
| Blog | none |
| Arxiv | https://arxiv.org/abs/1810.11654 |
Please fill the following table for the new friend sign …
=> 📰Poster - 3D MRI brain tumor segmentation using autoencoder regularization

docs/_pages/papers.md
#164
>
| --- | --- |
| Name | CornerNet: Detecting Objects as Paired Keypoints |
| Recommendation | THE ANCHOR FREE DETECTION|
| Publish | ECCV2018 |
| Author | Hei Law, et. al. |
| GitHub | [https://github.com/princeton-vl/CornerNet](https://github.com/princeton-vl/CornerNet) |
| Blog | …
=> 📰Poster - CornerNet: Detecting Objects as Paired Keypoints

docs/_pages/papers.md
#164 
>
| --- | --- |
| Name | Real-Time Monocular Pose Estimation of 3D Objects using Temporally Consistent Local Color Histograms |
| Recommendation | The demo is great for real-time 3D object tracking |
| Year | 2017 |
> Everyone will be welcome. You can join or not join as you want (not required by …
=> 📰Poster - Real-Time Monocular Pose Estimation of 3D Objects using Temporally Consistent Local Color Histograms

docs/_pages/papers.md
#176 
>
| --- | --- |
| Name | On Pixel-Wise Explanations for Non-Linear Classifier Decisions by Layer-Wise Relevance Propagation |
| Recommendation | Understand and interpret classification models |
> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change …
=> 📰Poster-On PixelWise Explanations for NonLinear Classifier Decisions by LayerWise Relevance Propagation

docs/_pages/papers.md
#176 
>
The Poster contains 3 main part all listed in the project link:
1. The project background info.
2. The project mind chart for planning.
3. The detailed plan for phase I. (to be defined.)
> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can …
=> 📰Poster - Magic Mirror Project Introduction and Kick Off Notification

docs/_pages/about.md, package.json
=> feat($docs/about.md): add video into about.md

docs/_pages/papers.md
> 📰Poster-Learning Deep Features for Discriminative Localization
https://github.com/BUPT/ai-ml.club/issues/189
| --- | --- |
| Name | Learning Deep Features for Discriminative Localization|
| Recommendation | shed light on how it explicitly enables the convolutional neural network to have remarkable localization ability despite being trained on image-level labels |
| Year | 2015 |
| Author | Bolei Zhou, et. al. |
<sub>
<i>
</i>
</sub>
=> 📰Poster-Learning Deep Features for Discriminative Localization

docs/_pages/manuals/chair.md, docs/_pages/papers.md
#189 
>
| --- | --- |
| Name | Finding Task-Relevant Features for Few-Shot Learning by Category Traversal |
| Recommendation | Preprocess in task level, nearly like spacial attention |
| Prior Knowledge| few-shot learning, RelationNetwork |
| Year |  2019 |
| Publish | CVPR |
| Author | Hongyang Li, et. al. |
| GitHub | …
=> 📰Poster - Finding Task-Relevant Features for Few-Shot Learning by Category Traversal

docs/_pages/papers.md
> https://github.com/BUPT/ai-ml.club/issues/189
>
| --- | --- |
| Name | Region Proposal by Guided Anchoring |
| Recommendation | Let the network learn the anchor itself |
| Prior Knowledge| object detection |
| Publish | CVPR |
| Author | Jiaqi Wang1∗ Kai Chen1∗ Shuo Yang2 Chen Change Loy3 Dahua Lin1 |
| GitHub | https: …
=> 📰Poster - Guided Anchor

docs/_pages/papers.md
#189 
| --- | --- |
| Name | High-Resolution Representations for Labeling Pixels and Regions |
| Recommendation | ONE_LINE_RECOMMENDATION |
| Prior Knowledge| KEYWORDS |
| 2019 | 2019 |
| Publish | CONFERENCE_OR_JOURNAL_NAME |
| Author | AUTHOR1, et. al. |
| GitHub | https://github.com/HRNet/HRNet-Object-Detection |
| Blog | BLOG_LINK |
| Arxiv | High-Resolution Representations for Labeling Pixels and Regions |
Please fill the following table for the new friend sign up(if any), or delete it.
<sub>
<i>
Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML …
=> 📰Poster - High-Resolution Representations for Labeling Pixels and Regions

docs/_pages/papers.md
#189
>
| --- | --- |
| Name | Attention in computer version |
| Recommendation | to rethink cnn |
| Prior Knowledge| CNN |
| Year | 2017-2019 |
| Publish |CVPR 2018  |
| Author | |
| GitHub | |
| Blog | https://blog.csdn.net/Arron_hou/article/details/95676716 |
| Arxiv | https://arxiv.org/abs/1709.01507 …
=> 📰Poster - Attention in computer version

docs/_people/vdeamov.md
When pull request, you can create a branch to pull request.(no more annoying commits)
```
git add .
git commit -m "message"
git push
```
```
git log  # find your commit
git checkout -b patch1 upstream/master # add branch and  link to upstream
git cherry-pick d689c083ac889b1cd09b03857502bb7508ce2cb8 # this is commit-id you find in log
git push origin patch1 # push, then pull request with this branch
```
Happy Coding
=> add vdeamov profile

docs/_pages/papers.md
#201
>
| --- | --- |
| Name | SMP2019-ECDT |
| Recommendation | Human-Computer Dialogue in practice |
| Prior Knowledge| GPT |
| Publish | CIPS-SMP |
| Blog | http://conference.cipsc.org.cn/smp2019/evaluation.html |
> Everyone will be welcome. You can join or not join as you want (not …
=> 🗣Oral  - The Evaluation of Chinese Human-Computer Dialogue Technology,SMP2019-ECDT

docs/_pages/papers.md
> Please copy/paste the title template from the following line:  
> 🗣Oral | 📰Poster - Paper Title  
> And delete this part before continue editing your PR
#201 
>
| --- | --- |
| Name | Few-Shot Generalization Across Dialogue Tasks |
| Recommendation | Learn the core technique of Rasa Core |
| Prior …
=> 📰Poster - Few-Shot Generalization Across Dialogue Tasks

docs/_people/newip.md
=> Update and rename xinhe.md to newip.md

docs/_data/authors.yml, docs/_people/arron.md
=> arron author message

docs/_pages/papers.md
> Please copy/paste the title template from the following line:  
> 🗣Oral | 📰Poster - Paper Title  
> And delete this part before continue editing your PR
> https://github.com/BUPT/ai-ml.club/issues/245
>
| Name            | 如何把博客图谱变成问答机器人                 |
| Prior Knowledge | NLP, …
=> 📰Poster 如何把博客图谱变成问答机器人

docs/_pages/papers.md
#245 
>
| Name            | Clinically applicable deep learning for diagnosis and referral in retinal disease    |
| Recommendation  | An AI framework could be used in the real medical world.    |
| Prior Knowledge | OCT, …
=> 📰Poster - Clinically applicable deep learning for diagnosis and referral in retinal disease

docs/_pages/papers.md
#264 
>
| Name            |Feature Selective Anchor-Free Module for Single-Shot Object Detection  |
| Recommendation  | anchor-free and feature selection adaptive  |
| Prior Knowledge | object detection  |
| Year …
=> 📰 Poster -  Feature Selective Anchor-Free Module for Single-Shot Object Detection

docs/_pages/papers.md
#264 
| Name            | Learning to Propagate Labels-Transductive Propagation Network for Few-Shot Learning                 |
| Recommendation  | Fist use graph in few-shot image classification    |
| Prior Knowledge | few-shot, GNN                   |
| Year            | 19               |
| Publish         | ICLR 2019 |
| Author          | Yanbin Liu, et. al.           |
| GitHub          | https://github.com/csyanbin/TPN               |
| Arxiv           | https://arxiv.org/abs/1903.00621                |
> Everyone will be welcome. …
=> 📰Poster - Learning to Propagate Labels-Transductive Propagation Network for Few-Shot Learning

docs/_pages/papers.md
#264
>
| Name            | Dual Attention Network for Scene Segmentation                 |
| Recommendation  | An efficient semantic segmentation structure    |
| Prior Knowledge | semantic segmentation                   | …
=> 📰Poster - Dual Attention Network for Scene Segmentation

docs/_posts/2019-08-11-seminar-meeting-minutes-3-1.md
=> S03E01 SUMMARY: fix teaser image

docs/_pages/manuals/okr.md
=> translate okr

docs/_pages/papers.md
📰Poster-Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps
<https://github.com/BUPT/ai-ml.club/issues/279>
| Name            | Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps |
| Recommendation  | This paper addresses the visualisation of image classification models, learnt using deep Convolutional Networks (ConvNets)    |
| Year            | 2014 |
| Author          |Karen Simonyan, et. al.           |
| Arxiv           | <https://arxiv.org/pdf/1312.6034.pdf> |
<sub>
<i>
Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a …
=> Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps

docs/_data/authors.yml, docs/_pages/manuals/chair.md, docs/_pages/manuals/member.md, docs/_people/newip.md
Update personal profile and fix 2 manual path erros.
=> Update personal profile and fix 2 manual path erros.

docs/_pages/papers.md
#293
>
| Name            | Pre-training BERT from scratch with cloud TPU                 |
| Recommendation  | Use free TPU on Colab    |
| Prior Knowledge | BERT                   | …
=> 📰Poster - Pre-training BERT from scratch with cloud TPU

docs/_pages/papers.md
> Please copy/paste the title template from the following line:
> 🗣Oral | 📰Poster - Paper Title
> And delete this part before continue editing your PR
#ISSUE_NUMBER
>
| Name            | Spider: A Large-Scale Human-Labeled …
=> Update papers.md with NL2SQL task

docs/_pages/papers.md
#320
>
| Name            | TensorFlow 2.0 with TPU Strategy                 |
| Recommendation  | TensorFlow 2.0 RC    |
| Prior Knowledge | N/A                   |
| GitHub …
=> 📰Poster - TensorFlow 2.0 with TPU Strategy

docs/_posts/2019-09-01-seminar-meeting-minutes-3-4.md
Fix pdf not shown error reference to #299
=> fix pdf for issue299

docs/_pages/papers.md
📰Poster - Building End-To-End Dialogue Systems Using Generative Hierarchical Neural Network Models
[#]()
| Name            | Building End-To-End Dialogue Systems Using Generative Hierarchical Neural Network Models               |
| Recommendation  | Basic Model of Multi-Turn Chatbot    |
| Prior Knowledge | Seq2Seq, WordEmbedding                   |
| Year            | 2016               |
| Publish         | AAAI |
| Author          | Iulian V. Serban, et. al.           |
| Arxiv           | https://arxiv.org/pdf/1507.04808.pdf                |
<sub>
<i>
Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a …
=> 📰Poster - Building End-To-End Dialogue Systems Using Generative Hierarchical Neural Network Models

docs/_pages/papers.md
#345  
>
| Name            | TensorFlow in JavaScript                 |
| Recommendation  | Use JS Everywhere!    |
| Prior Knowledge | TensorFlow & JavaScript / ES6 / TypeScript                   |
| Year            | 2019 …
=> 🗣Oral - TensorFlow in JavaScript: A Seq2seq Model in JS

docs/_posts/2019-09-22-seminar-meeting-minutes-3-7.md, docs/assets/2019/seminar-3-7/after-party.jpg, docs/assets/2019/seminar-3-7/architecture.gif, docs/assets/2019/seminar-3-7/chairs.jpg, docs/assets/2019/seminar-3-7/group.jpg, docs/assets/2019/seminar-3-7/guochengkai-predicting-prosodic-prominence-from-text.pdf, docs/assets/2019/seminar-3-7/guochengkai.jpg, docs/assets/2019/seminar-3-7/tensorflow-js.gif, docs/assets/2019/seminar-3-7/wanglinyu-vague-language.pdf, docs/assets/2019/seminar-3-7/wanglinyu.jpg, docs/assets/2019/seminar-3-7/zhanglu-e2e-generative-hierarchical-neural.pdf, docs/assets/2019/seminar-3-7/zhanglu.jpg, scripts/fit-image.sh
=> add s3e7 meeting minutes

docs/_pages/papers.md
#357
>
| Name            | Consensus-Driven Propagation in Massive Unlabeled Data for Face Recognition                 |
| Recommendation  | Semi-supervised face clustering using kNN graph and committee mechanism |
| Prior …
=> 🗣Oral - Consensus-Driven Propagation in Massive Unlabeled Data for Face Recognition

docs/_pages/papers.md
> 📰Poster-Visualizing the Hidden Activity of Artificial Neural Networks
<https://github.com/BUPT/ai-ml.club/issues/357>
| Name            | Visualizing the Hidden Activity of Artificial Neural Networks                 |
| Recommendation  | using dimensionality reduction for two tasks: visualizing the relationships between learned representations of observations, and visualizing the relationships between artificial neurons    |
| Year            | 2017               |
| Publish         | IEEE Transactions on Visualization and Computer Graphics |
| Author          | Paulo E. Rauber , et. al.           |
| Url           | https://ieeexplore.ieee.org/document/7539329                |
| Referrer | …
=> Visualizing the Hidden Activity of Artificial Neural Networks

docs/_posts/2019-09-15-seminar-meeting-minutes-3-6.md
=> fix 段嘉明 -> 段嘉铭

docs/_posts/2019-09-22-seminar-meeting-minutes-3-7.md
=> typo_fix for my name

docs/_pages/papers.md
#357 
>
| Name            | Transformer如戏，全靠Mask                 |
| Recommendation  | 用混淆矩阵的架构来分析 BERT / XLNET / SEQ2SEQ  底层的区别和联系  |
| Prior Knowledge | Transformer                   |
| Year            | 2019 …
=> 📰Poster - Transformer如戏，全靠Mask

docs/_pages/papers.md
#357 
>
| Name            | 人工智能，碳污染，及其解决方案                |
| Recommendation  | Tiny BERT / Energy and Policy Considerations for Deep Learning in NLP  |
| Prior Knowledge | Transformer / BERT / Knowledge Distillation …
=> 📰Poster - AI, Carbon Pollution and Its Solutions

docs/_pages/papers.md
#357
>
| Name            |25 Tweets to Know You: A New Model to Predict Personality with Social Media                |
| Recommendation  | Predict Personality by NLP   |
| Prior Knowledge | Word Embedding                  | …
=> 📰Poster - 25 Tweets to Know you

docs/_posts/2019-10-06-seminar-meeting-minutes-3-9.md
=> S3E10->S3E11

docs/_pages/papers.md
=> fix s3e8 paper's name

docs/_pages/papers.md
#367 
>
| Name            | FastFCN: Rethinking Dilated Convolution in the Backbone for Semantic Segmentation                 |
| Recommendation  | Applying mathematics and cybernetics knowledge to CNN model building     | …
=> 🗣Oral: FastFCN and Cybernetics(S03E10)

docs/_pages/papers.md
> 📰Poster-Visualizing the Hidden Activity of Artificial Neural Networks
<https://github.com/BUPT/ai-ml.club/issues/375>
| Name            | Visualizing the Hidden Activity of Artificial Neural Networks                 |
| Recommendation  |  using dimensionality reduction for two tasks: visualizing the relationships between learned representations of observations, and visualizing the relationships between artificial neurons.    |
| Year            | 2017              |
| Publish         |  IEEE Transactions on Visualization and Computer Graphics ( Volume: 23 , Issue: 1 , Jan. 2017 ) |
| Author          | Paulo E. Rauber, et. al. …
=> 📰Poster-Visualizing the Hidden Activity of Artificial Neural Networks

docs/_pages/papers.md
#367 
>
| Name            | “Why Should I Trust You?”Explaining the Predictions of Any Classifier                 |
| Recommendation  | Knowing how to explain your model    |
| Prior Knowledge | Machine Learning CNN …
=> 📰 Poster-“Why Should I Trust You?”Explaining the Predictions of Any Classifier 

docs/_pages/papers.md
#367 
>
| Name            | Induction Networks for Few-Shot Text Classification               |
| Recommendation  | Induction Networks  |
| Prior Knowledge | Induction Networks  |
| Year            | 2019   |
| Publish …
=> 📰Poster - Induction Networks for Few-Shot Text Classification

docs/_pages/papers.md
#389
>
| Name            | Recursive Sketches for Modular Deep Learning                |
| Recommendation  | 神经网络速写是一个被广泛研究的领域, 简洁地概括网络的操作似乎和模型可解释性有着密切的联系 |
| Prior Knowledge | The Space Complexity of Approximating The …
=> 📰Poster S03E12: Recursive Sketches for Modular Deep Learning

docs/_pages/papers.md
#389 
>
| Name            | [Generative Code Modeling With Graphs](https://arxiv.org/pdf/1805.08490.pdf)   |
| Recommendation  | new way for code generating using graph  |
| Prior Knowledge | GNN |
| Year            |  2019 …
=> 📰Poster - Generative Code Modeling With Graphs

docs/_pages/papers.md
📰Poster - A Brief Review of Evaluation for Chatbot systems
#375 
| Name            | A Brief Review of Evaluation for Chatbot Systems                |
| Recommendation  | know  evaluation for chatbot systems     |
| Prior Knowledge |    evaluation of generative tasks , chatbot              |
<sub>
<i>
</i>
</sub>
=> 📰Poster - A Brief Review of Evaluation for Chatbot Systems

docs/_pages/papers.md
=> Fix: typo in papers.md

docs/_pages/papers.md
>📰Poster-VISUALIZING DEEP NEURAL NETWORK DECISIONS: PREDICTION DIFFERENCE ANALYSIS
<https://github.com/BUPT/ai-ml.club/issues/407>
| Name            | VISUALIZING DEEP NEURAL NETWORK DECISIONS: PREDICTION DIFFERENCE ANALYSIS                 |
| Recommendation  | When classifying images, the method highlights areas in a given input image that provide evidence for or against a certain class   |
| Year            | 2017               |
| Publish         | ICLR |
| Author          | Luisa M Zintgraf, et. al.           |
| GitHub          | <https://github.com/lmzintgraf/DeepVis-PredDiff>              |
| Arxiv           | <https://arxiv.org/pdf/1702.04595v1.pdf>                 | …
=> 📰Poster-VISUALIZING DEEP NEURAL NETWORK DECISIONS: PREDICTION DIFFERENCE ANALYSIS

docs/_pages/papers.md
#413 
>
| Name            | An Empirical Study of Spatial Attention Mechanisms in Deep Networks                 |
| Recommendation  | Toward a better general understanding of attention mechanisms    |
| Prior Knowledge | …
=> 📰Poster - An Empirical Study of Spatial Attention Mechanisms in Deep Networks

docs/_pages/papers.md
#426 
>
| Name            | Deep Learning in Spiking Neural Networks                 |
| Recommendation  | Referred by @huan SNN looks better for energy efficiency and high coding strategy for future benefit.    |
| Year …
=> 📰Poster - Deep Learning in Spiking Neural Networks (Round 1)

docs/_pages/papers.md
#426 
>
| Name            | Improving Multi-turn Dialogue Modelling with Utterance ReWriter                 |
| Recommendation  | rewriting the human utterance as a pre-process to help multi-turn dialgoue modelling    |
| …
=> 📰Poster - Improving Multi-turn Dialogue Modelling with Utterance ReWriter

docs/_pages/papers.md
#426 
>
| Name            | Visualizing and Measuring the Geometry of BERT                 |
| Recommendation  | BERT    |
| Prior Knowledge | BERT                   |
| Author …
=> 📰Poster -  Visualizing and Measuring the Geometry of BERT

docs/_pages/papers.md
#441 
> I comment here due to that blog pr didn't merge right now.
>
| Name            | PAPER_NAME                 |
| Recommendation  | Few-shot Learning basic problem settings    |
| Prior Knowledge | few-shot learning, image classification                  |
| Year            | …
=> 📰Poster - Brief Roadmap for Few-shot Image Classification

docs/_pages/papers.md
#ISSUE_NUMBER
>
| Name            | PAPER_NAME                 |
| Recommendation  | Optimization-based Meta-Learning approach    |
| Prior Knowledge | MAML, LEO              |
| …
=> 📰Poster - Optimization-Based Meta-Learning

docs/_pages/papers.md
=> fix name for xingximing

docs/_pages/papers.md
#460 
>
| Name            | TASK2VEC: Task Embedding for Meta-Learning       |
| Recommendation  | interesting method to measure the backbone |
| Prior Knowledge | few-shot learning                  |
| Publish         | ICCV |
| Author …
=> 📰Poster - TASK2VEC: Task Embedding for Meta-Learning

docs/_pages/papers.md
#459 
>
| Name            | Generating Sentences from a Continuous Space                 |
| Recommendation  | it is able to generate coherent and diverse sentences through purely continuous sampling and provides …
=> 📰Poster - Generating Sentences from a Continuous Space

docs/_pages/papers.md
#459 
>
| Name            | Language Models are Unsupervised Multitask Learners                 |
| Recommendation  | GPT-2    |
| Prior Knowledge | language model                   |
| Year            | 2019              | …
=> 📰Poster-Language Models are Unsupervised Multitask Learners

docs/_pages/papers.md
> Please copy/paste the title template from the following line:
> 🗣Oral | 📰Poster - Paper Title
> And delete this part before continue editing your PR
#ISSUE_NUMBER
>
| Name            | Distilling the Knowledge in a Neural …
=> 🗣Oral - Distilling the Knowledge in a Neural Network

docs/_pages/manuals/newcomer.md
=> add google group docs for newcomer
